baseURL = "http://wehrend.uber.space/"
languageCode = "en-us"
title = "Bits & pieces - Sven Wehrend"
theme = "hugo-book"

[Languages]
[Languages.en]
Languagename = 'English'
[[Languages.en.menu.before]]
  name = "Web-Blog"
  contentDjr = "/en/posts/web/"
  weight = 10

[[Languages.en.menu.before]]
  name = "Synth-Blog"
  contentDir = "/en/tags/synth/"
  weight = 20


[[Languages.en.menu.before]]
  name = ""
  contentDir = "/en/docs/"
  weight = 10


[[Languages.en.menu.before]]
  name = "Electronics 101"
  contentDir = "/en/pages/prequel-short-introduction-to-electronics"
  weight = 26

[[Languages.en.menu.before]]
  name = "Electronics 102"
  contentDir  = "/en/pages/short-introduction-to-electronics-102"
  weight = 27


[[Languages.en.menu.after]]
  name = "Digital Logic 1 (Overview)"
  contentDir= "/en/pages/overview/"
  weight = 20

[[Languages.en.menu.before]]
  name = "Digital Logic 2 (Overview)"
  contentDir = "/en/pages/overview2/"
  weight = 25

[[Languages.en.menu.after]]
  name = "About"
  contentDir = "/en/pages/about/"
  weight = 10

[Languages.de]
Languagename='Deutsch'
[[Languages.de.menu.before]]
  name = "Web-Blog"
  contentDir = "/de/posts/web/"
  weight = 10

[[Languages.de.menu.before]]
  name = "Synth-Blog"
  contentDir = "/de/tags/synth/"
  weight = 20


[[Languages.de.menu.before]]
  name = ""
  contentDir = "/de/docs/"
  weight = 10


[[Languages.de.menu.before]]
  name = "Elektronik 101"
  contentDir = "/de/pages/prequel-short-introduction-to-electronics"
  weight = 26

[[Languages.de.menu.before]]
  name = "Elektronik 102"
  contentDir = "/de/pages/short-introduction-to-electronics-102"
  weight = 27


[[Languages.de.menu.after]]
  name = "Digitale Logik 1 (Übersicht)"
  contentDir = "/de/pages/overview/"
  weight = 20

[[Languages.de.menu.before]]
  name = "Digitale Logik 2 (Übersicht)"
  contentDir = "/de/pages/overview2/"
  weight = 25

[[Languages.de.menu.after]]
  name = "Über mich "
  contentDir = "/de/pages/about/"
  weight = 35

[[frontmatter]]
    date = "filename"

[params]

  BookSection = "/en/docs"
  date_format = "2006-01-02"
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = false


[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$', '^asciidoctor$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

[markup.asciidocext]
    extensions = ["asciidoctor"]
    workingFolderCurrent = true
    trace = true
    verbose = true