baseURL = "http://wehrend.uber.space/"
languageCode = "en-us"
title = "Bits & pieces - Sven Wehrend"
theme = "hugo-book"


[Languages]
[Languages.en]
title = "Multilingual Hugo Example"
weight = 0
languagename = "English"


[[languages.en.menu]]
  name = "Web-Blog"
  url = "/posts/web/"
  weight = 10

[[languages.en.menu]]
  name = "Synth-Blog"
  url = "/tags/synth/"
  weight = 20


[[languages.en.menu]]
  name = "docs"
  url = "/docs/"
  weight = 10

  
[[languages.en.menu]]
  name = "Electronics 101"
  url = "/pages/prequel-short-introduction-to-electronics"
  weight = 26

[[languages.en.menu]]
  name = "Electronics 102"
  url = "/pages/short-introduction-to-electronics-102"
  weight = 27


[[languages.en.menu]]
  name = "Digital Logic 1 (Overview)"
  url = "/pages/overview/"
  weight = 20

[[languages.en.menu]]
  name = "Digital Logic 2 (Overview)"
  url = "/pages/overview2/"
  weight = 25


[languages.de]
title = "Multilingue Exemple Hugo"
weight = 1
languagename = "Deutsch"

[[languages.de.menu]]
  name = "Elektronik 101"
  url = "/pages/prequel-short-introduction-to-electronics-de"
  weight = 19

[[languages.de.menu]]
  name = "Elektronik 102"
  url = "/pages/short-introduction-to-electronics-102-de"
  weight = 20

[[languages.en.menu]]
  name = "About"
  url = "/pages/about/"
  weight = 10

[[languages.de.menu]]
  name = "Über mich"
  url = "/pages/ueber/"
  weight = 10

  
[params]
  date_format = "2006-01-02"
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  BookTheme = 'light'

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC = false


[security.exec]
    allow = ['^(dart-)?sass(-embedded)?$', '^go$', '^git$', '^npx$', '^postcss$', '^tailwindcss$', '^asciidoctor$']

[markup.asciidocext]
    extensions = ["asciidoctor"]
    workingFolderCurrent = true
    trace = true
    verbose = true
