.. title: How does a CPU work? Excursion to Memory
.. slug: how-does-a-cpu-work-memory
.. date: 2022-01-09
.. category:
.. link: 
.. description: 
.. type: text

== Memory Organization
In this blog post the author will introduce the different
types of semiconductor memory. This is a wide field, 
so the goal here is to focus on the most important ones 
and draw the differences between the different types.

=== The Memory hierarchy 

As in computing all is about performance, we first have a look 
at the memory hierarchy. As you can see in the pyramid below, memory is 
ordered in layers. The slowest elements -also the ones with highest 
latency - are at the bottom of this pyramid, while the fastest ones are 
shown at the apex.
Imagine your desk is the actual CPU, with an open book laying in front of your
eyes. This is the register. Now you read in this book a reference to another book
in your bookshelf. Your bookshelf is the cache here. The cache itself is again layered.
Lets say L1-cache is the bookshelf in your room, L2-cache the bookshelf in another room
and L3-cache books stored in a box in the same room. If you now have a reference
in your current book (the one on your desk), that refers to a book you do not possess, you need to
go to the public library. The public library is your RAM. The access times are really high. 
And lets say the book you need is also not available there, and they must order it from a library 
in another city. Then you got to the level at the bottom, which is the disk storage unit.

image:../images/how_does_cpu/memhierarchy.svg[width="100%"]

At the bottom is also the low-priced memory (per byte). 
The higher you go on the hierarchy the costlier the memory becomes.
In this article we will expand our knowledge about the RAM. 
Caches are more complex and will eventually be handeled in a future 
article.

=== RAM and ROM
The image below shows the overall organization of a ram circuit,
RAM stand for random access memory, so it means a memory with arbitrary
access. Simply put, you set an address in and get the data which is stored 
under the given address location out.The schematic given here also holds for
Read only memory (ROM). Complementary to ROM, which is persistent, RAM 
is volatile. So it needs ongoing power supply,otherwise it loses
its stored data.

image:../images/how_does_cpu/ram_schematic.svg[width="90%"]

As can be seen the main parts apart from the memory itself
are column- and row-decoder, as well as read / write amplifier.
The address-decoder just consists of well-known combinatorial logic,
while the amplifier are a bit more complex.
The blue dots on the intersection of rows and columns mark the
placements of the memory cell, depending on the type of memory,
those differ and are explained in the next section.

==== The different memory cells


[cols="a,a" width="100%"]
|===
| static RAM (SRAM)  | dynamic RAM (DRAM)
| image:../images/how_does_cpu/sram_nmos.svg[width="100%"] 
| image:../images/how_does_cpu/dram.svg[width="100%"]
| transistor # 4 | transistor # 1 
|image:../images/how_does_cpu/sram_cmos.svg[width="100%"] |
| transistor # 6 |
|===

==== The bus cycle
The bus cycles are highly specific on the chosen CPU and / or implementation, 
so here we can only show the essentials. 
For this example to show the fundamentals of read and write
cycle the author chose the Zilog (R) Z80 processor. We will only have 
a look onto the surface here and not discuss things like direct memory access (DMA).
The Z80 is a somewhat simple processor, designed 1976.

*Memory pins*
[cols="a,a,a",autowidth,options="header"]
|===
| Pin(s)   | Description         | Comment
| A0 - An  | Address lines / bus | 
| D0 - Dn  | Data lines / bus    |
| /CE | Chip Enable (low-active) | Enable the chip; also known as Chip Select (/CS)
| /OE | Output Enable (low-active) | Enable the data output 
| /WE | Write Enable (low-active) | Enable write cycle 
|===

*Zilog Z80 - overview of memory relevant pins*
[cols="a,a,a" autowidth options="header"]
|===
| Pin(s)   | Description         | Comment
| Clk      | Clock               |
| /MREQ    | Memory Request (low-active) |
| A0 - A7  | Address lines / bus | 
| D0 - D7  | Data lines / bus    |
| /M1      | machine cycle 1 (low-active) | instruction fetch cycle
| /RD | Read (low-active)  | read operation
| /WR | Write (low-active) | write operation
| /RFSH | Refresh (low-active) | Refresh for DRAM
| /WAIT | Wait (low-active) | use wait-cycles
|===


image:../images/how_does_cpu/m1_cycle.svg[width="80%"] 
image:../images/how_does_cpu/m2m3_cycle.svg[width="80%"] 

