.. title: How does a CPU work? Overview
.. slug: how-does-a-cpu-work-overview
.. date: 2020-12-20
.. tags: 
.. category:
.. link:
.. description:
.. type: text

= How does a CPU work - Table of contents

==  *Introduction and overview*

_Introduction and overview_

Every topic of this course is broken up into two parts:
A part about the mathematical side of digital logic,
ideally almost independent from implementation details
and a more practical part handling this very details.


==  *A first look at digital logic*

_Boolean Algebra, basic logic gates and their implementation_

In this lesson we will discover truth tables, boolean notation and learn about
De Morgan's laws.
Also we have a look at the most basic logic gates and why their are usually are not
implemented as such in electronics, having a look at NAND and NOR instead.

==  *You have to choose!*

_A complex gatter: XOR_

Another CPU instrucion and as a side-note and preparation for the next topic, 
we have a look at the XOR gate. As in the first lesson we'll see first the logic 
part and then its translation into an electrical implementation.


==  *1+1 = 2*

_Binary systems (Part I) and Combinatorial Logic (Part I)_

Here we explain the basic concept of how to count with only two different states at hand.
Also we will learn how to sum up two positive integer values in the binary system, derivate
the logic needed for a full-adder, to dive into the topic of combinatorial logic.


==  *Let me look that up*

_First look into Memory and Look-Up-Tables (LUTs)_

In this lesson we learn, that - in principal - every form of combinatorial logic
can be transformed into 'software' by putting it into memory. In a practical example we will
show how a DDS sine wave generator use a Look-Up-Table (LUT) to replicate the sine.


==  *There is plenty room in the negative space*

_Binary Systems (Part II) signed integer_

Second part about the binary system. In this post we learn one- and two-
complement, endianess and about conversion to hex.


==  *Adding is not all*

_Combinatorial Logic (Part II), a simple ALU_

We want close the first series by this second chapter about combinatorial logic.
We will use our new knowledge of the signed integer adding a subtract functionality
to our adder and also extending the adder to a full ALU


==  *Outline, what comes next*

_From combinatorial to sequential_

In this first course we learned some basics about digital logic. But all these examples
use only static logic, we are still lacking a concept of how to store computed values.
We need to learn the concept of registers and sequential logic.
This will be the main topic of the second post series.
