---
title: X0_multiplication
date: 2022-04-24
category:
link: 
description: 
tags: draft
type: text
---

== Multiplication and Divsion

Multiplication operations can be implemented in very
different ways: Slow, as a serial operation, controlled by a 
micro program or fast in dedicated hardware. 

The division is a more complex operation, and will be discussed 
in another post.


=== Shift left and shift left

For integer numbers that are unsigned.

For multipliers that are powers of two, the operation is very 
simple and can be implemented via a shift left.

*A shift left by one bit equals a multiplication by 2, as left shift by n
bits equals a multiplication by 2^n.*

*A shift right is a division by 2, a right shift by n bits
is a division by 2^n*

image:../images/how_does_cpu/arithmetic_shift.svg[width=90%]

=== The multiplication algorithm 

To start with, we analyze the steps of a binary multiplication, which frankly does not differ much 
from a multiplication in the decimal system and is even simpler. We multiply 7 times 6 in the binary
system which results in 42.

multiplicand x multiplier = product

["latex","../images/multiplication.svg",imgfmt="svg", width="70%"]
\[ \begin{aligned}
0111_2 \times 0110_2 \\
\hline 0000   \\
011110 \\
011100 \\
0111000 \\
\hline 0101010 \\
\end{aligned} \]

As we can see, based on that example, the multiplication is a sequence of shifting and addition. 
With this groundwork, we can now dissect the multiplication operation and derive an algorithm from it.

